[workspace]
members = [
    "crates/protocol",
    "crates/agent",
    "crates/gui",
    "crates/cli",
    "crates/game",
]
resolver = "2"

[workspace.package]
version = "0.6.0"
edition = "2021"

[workspace.dependencies.dll-syringe]
version = "0.15"
features = [
    "rpc-payload",
    "payload-utils",
]

[workspace.dependencies.thiserror]
version = "1"

[workspace.dependencies.tracing]
version = "0.1"

[workspace.dependencies.windows]
version = "0.58.0"
features = [
    "Win32_System_LibraryLoader",
    "Win32_Foundation",
]

[workspace.dependencies.broadsword]
git = "https://github.com/vswarte/broadsword.git"

[workspace.dependencies.protocol]
path = "crates/protocol"

[workspace.dependencies.agent]
path = "crates/agent"

[workspace.dependencies.gui]
path = "crates/gui"

[workspace.dependencies.cli]
path = "crates/cli"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"
