[workspace]
members = [
    "gui",
    "agent",
]
resolver = "2"

[workspace.dependencies]
# I refer to the GH repo directly until https://github.com/OpenByteDev/dll-syringe/issues/10 is merged
dll-syringe = { git = "https://github.com/OpenByteDev/dll-syringe.git", rev = "0508b0f" }